### ISSUE TITLE
Support multiple schemes

### ISSUE THREAD

**Issue by gfontenot** [gfontenot/vim-xcodebuild#2]
Right now we just pick up the first available scheme, which isn't ideal. It'd be better if we could somehow let users choose which scheme to build.

**Comment by keith** [comment]
Step 1 on this could just be using the list of available specs as autocomplete arguments to one of the commands. If you saved the last scheme I feel like that could be good enough.

**Comment by gfontenot** [comment]
maybe it should be explicit? `XSelectScheme` as a new command?

**Comment by keith** [comment]
How about just setting a var for this. This way users could in theory have local `vimrc` files that set the scheme correctly. I suppose you could still have the command for ease of use though, especially if it did the autocomplete.

**Comment by gfontenot** [comment]
I think that probably makes sense for an MVP implementation. I think that it does make sense to expose a command though. I can definitely see the need to switch on the fly.

For example:

When working in Runes, the mac target is picked first, which is great because that's the target I like building/testing against. It's just a touch faster. But when working in Argo, we pick the iOS target. Setting a variable would be great, because then I'd be able to help out `xcodebuild.vim` here, but that wouldn't be a replacement for being able to set the scheme to the Mac target.

**Comment by keith** [comment]
Sounds good to me

**Comment by gfontenot** [comment]
Actually, this might cause issues with #15. If users change that variable at runtime, the scheme would be out of sync with the chosen sdk. With a command, we could be sure to reset both of those at the same time, given a provided scheme.

I do thin we _might_ want to provide some way to specify the scheme at initial launch, but I'm not sure it should be something that we allow to be changed at runtime.

**Comment by gfontenot** [comment]
Done in #23, continuing discussion of autocompletion in #24
