### ISSUE TITLE
Introduce `XRun` command

### ISSUE THREAD

**Issue by gfontenot** [gfontenot/vim-xcodebuild#22]
For iOS projects, this should use the `XBuild` command to build the project, then use `simctl` (`xcrun simctl`) to install the app.

```
# build
xcrun simctl install booted <path to built app>
xcrun simctl launch booted <app identifier> # this might be problematic
```

simctl usage:

```
Usage: simctl [--noxpc] [--set <set path>] <subcommand> ... | help [subcommand]
Command line utility to control the Simulator

For subcommands that require a <device> argument, you may specify a device UDID
or the special "booted" string which will cause simctl to pick a booted device.
If multiple devices are booted when the "booted" device is selected, simctl
will choose one of them.

Subcommands:
        create              Create a new device.
        delete              Delete a device or all unavailable devices.
        pair                Create a new watch / phone pair.
        unpair              Unpair a watch and phone phone.
        erase               Erase a device's contents and settings.
        boot                Boot a device.
        shutdown            Shutdown a device.
        rename              Rename a device.
        getenv              Print an environment variable from a running device.
        openurl             Open a URL in a device.
        addphoto            Add photos to the photo library of a device.
        install             Install an app on a device.
        uninstall           Uninstall an app from a device.
        get_app_container   Print the path of the intsalled app's container
        launch              Launch an application by identifier on a device.
        spawn               Spawn a process on a device.
        list                List available devices, device types, runtimes, or device pairs.
        icloud_sync         Trigger iCloud sync on a device.
        help                Prints the usage for a given subcommand.
```

**Comment by gfontenot** [comment]
So the process (in theory) is this:
- Boot an iOS simulator (`xcrun simctl boot <UUID>`)
- Install app in simulator (`xcrun simctl install booted <PATH>`)
- launch the app in the simulator (`xcrun simctl launch <BUNDLE_IDENTIFIER>`)

if we want to give users a choice of simulator (maybe `g:xcodebuild_ios_simulator` or `XSetSimulator`), we can get a list of options with `xcrun simctl list devices`.

This is all great, except that doing a simple install hangs for me and never finishes.

**Comment by gfontenot** [comment]
the nice thing is that I _think_ this will be simpler for OS X: `open -a build/MyCoolApp.app`

Determining the target name is still going to be a pain in the ass, even if we don't need to figure out the bundle identifier.

**Comment by gfontenot** [comment]
`simctl` seems _horribly_ broken. I can't get any of this to work.

**Comment by gfontenot** [comment]
[ios-sim](https://github.com/phonegap/ios-sim) seems to still work, I should be able to look into it and their [node wrapper around simctl](https://github.com/appium/node-simctl) to figure out what to do/what I'm doing wrong.

**Comment by gfontenot** [comment]
Looks like most of the bugs I ran into were from Xcode 7? I got a working prototype of this working as a shell script.

Other things to think of:
- Can we tell the difference between a Mac `.app` and an iOS `.app`?
- How do we help people not try launching iPad apps in an iPhone sim? Do we care?
- How are watch or TV apps handled?

I think we can punt on these for MVP

**Comment by mokagio** [comment]
>  I got a working prototype of this working as a shell script.

Using `ios-sim` or `simctl`? Any chance you could share a gist? I'm trying to automate installing and launching a build app into a Simulator and haven't been able to achieve it without `ios-sim` :disappointed: 

Thanks :smile:

**Comment by gfontenot** [comment]
I was able to get something working with bare `simctl`, which is important because I'd like to avoid adding external dependencies to this project.

I _believe_ [this is the working prototype](https://github.com/gfontenot/vim-xcode/blob/b9126a89a0fa7eb5c0f580134e094a6b48c21b9f/bin/run_ios_app.sh) although it's been a while since I've tried it so it might be broken.

**Comment by mokagio** [comment]
@gfontenot Thanks for pointing me to it.

Your script works great 👍
