### ISSUE TITLE
Add autocompletion for `:XSelectScheme`

### ISSUE THREAD

**Issue by gfontenot** [gfontenot/vim-xcodebuild#24]
With #23, we're letting users explicitly set the scheme to test or build. That's fantastic, but it would be _really_ great to add some autocompletion to improve the user experience.

This would probably entail changing the scheme finding script to return a list of schemes instead of a single scheme, and then caching that list.

**Comment by keith** [comment]
There's a problem with this right now since the `find_scheme.sh` script only searches through the project. Not any possible workspace.

**Comment by gfontenot** [comment]
Is that an issue? Do we _want_ to search the workspace? I was basically following Carthage's lead here, and it seemed reasonable. The workspace will most likely be littered with dependency schemes, but we can focus on the current project's schemes in the top level project file.

Maybe this is naive of me? I've never needed more than this.

**Comment by keith** [comment]
I occasionally use workspace schemes for development dependencies via CocoaPods. I would also imagine you would use these if you were manually maintaining a workspace with multiple projects and trying to rebuild subprojects individually.

**Comment by gfontenot** [comment]
I guess it makes sense in hindsight, but I'm kind of surprised that the output for `xcodebuild -list` for a workspace is actually _only_ schemes:

```
❯ xcodebuild -list -workspace Argo.xcworkspace
Information about workspace "Argo":
    Schemes:
        Argo-iOS
        Argo-Mac
        Argo-watchOS
        Curry-iOS
        Curry-Mac
```

Obviously we'll have to support both, though. I don't think that's a huge deal since schemes are always the last thing listed, though.
