### ISSUE TITLE
xcodebuild can fail and xcpretty will be like "A OK EVERYTHING IS COOL BRO"

### ISSUE THREAD

**Issue by gfontenot** [gfontenot/vim-xcodebuild#5]
Because we don't have anything setting `-o pipefail`, if `xcodebuild` fails, `xcpretty` will still succeed, which isn't awesome. I don't know if this will be a huge issue, but it's probably worth noting.

**Comment by mokagio** [comment]
_Note_: I have no idea of how Vim scripting works, so sorry if this is pointless, but... what about having `s:xcpretty_flags` add `&& exit ${PIPESTATUS[0]}` as the very last _flag_? See [xcpretty usage](https://github.com/supermarin/xcpretty#usage).

**Comment by gfontenot** [comment]
That's a great idea. The other way would be to prefix all of the commands with `set -o pipefail;`, I believe.

**Comment by mokagio** [comment]
Oh right, both option _should_ be legit.
