### ISSUE TITLE
Properly handle projects/workspaces with spaces in the name

### ISSUE THREAD

**Issue by gfontenot** [gfontenot/vim-xcodebuild#55]
We aren't doing this correctly everywhere right now.

**Comment by gfontenot** [comment]
I think right now we're just messing it up for the run actions.

**Comment by sharplet** [comment]
This should include scheme names with spaces, too.

**Comment by gfontenot** [comment]
I wonder if someone like @gabebw or @pbrisbin have ideas here. We're passing the scheme and workspace/project to the `run_ios_app` script correctly, and then using `$@` to pass those to the `xcodebuild` command, but it seems like the quotes are getting stripped somewhere along the line.

**Comment by gfontenot** [comment]
More specifically:
- We're [creating the command here](https://github.com/gfontenot/vim-xcode/blob/master/plugin/xcode.vim#L138).
- `s:build_target_with_scheme` is calling out to [`s:scheme`](https://github.com/gfontenot/vim-xcode/blob/master/plugin/xcode.vim#L198)
- `s:cli_args` [uses `shellescape` to escape the values properly](https://github.com/gfontenot/vim-xcode/blob/master/plugin/xcode.vim#L29-L31)
- We're [passing the arguments to `xcodebuild` with `$@`](https://github.com/gfontenot/vim-xcode/blob/master/bin/run_ios_app#L5)

My assumption is that by the time the flags get to `$@` they have lost the quotes, but I'm not sure how to fix that.

**Comment by gabebw** [comment]
The part that jumps out to me is that in [your last link](https://github.com/gfontenot/vim-xcode/blob/master/bin/run_ios_app#L5), `$@` isn't quoted like `"$@"`.

I [wrote about the differences](http://gabebw.com/blog/2015/11/29/command-line-arguments-in-shell-scripts), but the idea is that `$@` without quotes doesn't respect quotes even if the arguments are quoted.

**Comment by gabebw** [comment]
shellcheck agrees:

```
$ shellcheck run_ios_app 

In run_ios_app line 5:
build_path=$(xcodebuild -showBuildSettings $@ 2>/dev/null | egrep "\bBUILD_DIR\b" | sed -E "s/[[:space:]]+BUILD_DIR = //")
                                           ^-- SC2068: Double quote array expansions to avoid re-splitting elements.
```

**Comment by gabebw** [comment]
shellcheck found the same problem in `run_mac_app` too:

```
$ shellcheck run_mac_app 

In run_mac_app line 3:
build_path=$(xcodebuild -showBuildSettings $@ 2>/dev/null | egrep "\bBUILD_DIR\b" | sed -E "s/[[:space:]]+BUILD_DIR = //")
                                           ^-- SC2068: Double quote array expansions to avoid re-splitting elements.
```

**Comment by gabebw** [comment]
shellcheck found the same problem in some of the other scripts in `bin`. This is the full output:

```
$ shellcheck bin/*

In bin/list_schemes.sh line 5:
xcrun xcodebuild -list $@ 2>/dev/null \
                       ^-- SC2068: Double quote array expansions to avoid re-splitting elements.


In bin/run_ios_app line 5:
build_path=$(xcodebuild -showBuildSettings $@ 2>/dev/null | egrep "\bBUILD_DIR\b" | sed -E "s/[[:space:]]+BUILD_DIR = //")
                                           ^-- SC2068: Double quote array expansions to avoid re-splitting elements.


In bin/run_mac_app line 3:
build_path=$(xcodebuild -showBuildSettings $@ 2>/dev/null | egrep "\bBUILD_DIR\b" | sed -E "s/[[:space:]]+BUILD_DIR = //")
                                           ^-- SC2068: Double quote array expansions to avoid re-splitting elements.


In bin/use_simulator.sh line 5:
xcrun xcodebuild -showBuildSettings $@ 2>/dev/null \
                                    ^-- SC2068: Double quote array expansions to avoid re-splitting elements.
```

**Comment by gfontenot** [comment]
Ah, I didn't realizing that quoting `$@` worked that way. Neat. I should look into getting ci set up to run shellcheck against PRs.

**Comment by pbrisbin** [comment]
> I should look into getting ci set up to run shellcheck against PRs.

You could also use Code Climate :D

https://codeclimate.com/github/pbrisbin/aurget/issues

**Comment by pbrisbin** [comment]
In addition to the shellcheck engine, there's also [vint](https://docs.codeclimate.com/docs/vint). I'm not sure how good it is, but worth a shot.
