### ISSUE TITLE
Error using `Xrun`

### ISSUE THREAD

**Issue by sharplet** [gfontenot/vim-xcodebuild#60]
I haven't been able to successfully run in the simulator yet. Here's the output I'm seeing:

```
find: ftsopen: No such file or directory
2016-07-12 17:58:49.918 defaults[19684:4476942] 
The domain/default pair of (/Info, CFBundleIdentifier) does not exist
```

I'm going to dig around in the code to see if I can work out what's going wrong.

**Comment by sharplet** [comment]
I think this might be a symptom of #27.

**Comment by gfontenot** [comment]
Yeah, that'd be my bet. Let's leave this open till that one's resolved so we can verify.
