### ISSUE TITLE
Vundle install error but still works

### ISSUE THREAD

**Issue by hoang-tran** [gfontenot/vim-xcodebuild#61]
I succeeded install xcode.vim via Vundle in my first time. But for subsequent attempts, it pops out this error:

```
Error detected while processing ~/.vim/bundle/vim-xcode/plugin/xcode.vim:
line   55:
E122: Function <SNR>87_run already exists, add ! to replace it
```

However, I'm still able to use the plugin normally. It's just an annoying alert whenever vundle executed. Does anybody have this issue?

**Comment by keith** [comment]
Ah looks like `s:run`'s function is missing a `!`

**Comment by keith** [comment]
Submitted a fix here: https://github.com/gfontenot/vim-xcode/pull/63

**Comment by hoang-tran** [comment]
Wow, nice. Thanks @keith

**Comment by gfontenot** [comment]
This should be fixed on master now. Sorry about that!
