### ISSUE TITLE
Build and Run

### ISSUE THREAD

**Issue by gfontenot** [gfontenot/vim-xcodebuild#68]
Unfortunately, we're currently requiring users to build the app then run it as two different steps. This kinda sucks, and it'd be better if we could have some kind of build and run option.

Since we don't actually know _when_ the build command finishes, it's probably best to generate the build command and the run command then send them _both_ to the runner as `build && run`.

**Comment by gfontenot** [comment]
Thinking about this more: It probably makes more sense for `Xrun` to default to building the app first. That would be much more intuitive. In theory we could introduce some way to run without building later, but it seems much less important.

**Comment by sharplet** [comment]
> It probably makes more sense for `Xrun` to default to building the app first.

👍 That would line up well with Xcode's behaviour. I'm not sure many people even know about the run-without-building option in Xcode.
