### ISSUE TITLE
Fails to find xcproject file?

### ISSUE THREAD

**Issue by regnerjr** [gfontenot/vim-xcodebuild#78]
I have an Xcode project, cd there. Then open it with `vim .` because I want to try out this swell tool.

Anyway `:Xbuild` fails on first try. 

```
Error detected while processing function <SNR>33_build..<SNR>33_assert_project..<SNR>33_project_files:
line    1:
E118: Too many arguments for function: globpath
E15: Invalid expression: globpath(expand('.'), '*.xcodeproj', 0, 1)
Error detected while processing function <SNR>33_build..<SNR>33_assert_project..<SNR>33_workspace_files:
line    1:
E118: Too many arguments for function: globpath
E15: Invalid expression: globpath(expand('.'), '*.xcworkspace', 0, 1)
No Xcode project file found!
```

My guess is that this is because of spaces in the name of my project file.  Not sure where to start debugging beyond just my guess. 

Project name is "WM To Go.xcodeproj" (Also no there is no .xcworkspace, cocoapods is configured on the other branch)

**Comment by gfontenot** [comment]
Interesting. I thought we were handling this properly. Can you remove the spaces (just replace them with `-` or something) to confirm that the spaces are causing the problem? If that doesn't fix the issue can you post a list of the files in the root of the repo?

**Comment by gfontenot** [comment]
Oh actually, I wonder if the issue here is your version of vim. It looks like it's blowing up because we're using a version of `globpath` that you don't have access to. Would you mind posting the result of `vim --version`?

**Comment by regnerjr** [comment]
Hi Gordon, Thanks for the help.
You are correct, my path was pointing to the system version of vim

```
VIM - Vi IMproved 7.3 (2010 Aug 15, compiled Jun 14 2016 16:06:49)
Compiled by root@apple.com
```

and not the shiny one installed from homebrew. 

```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Aug 23 2016 17:01:27)
MacOS X (unix) version
Included patches: 1-2235
Compiled by Homebrew
Huge version without GUI.  Features included (+) or not (-):
```

Thanks again for the help.
Really excited to try this out. It might be time to finally get serious about my vim-ing.

**Comment by gfontenot** [comment]
Fantastic news. Please feel free to open up any issues if you run into any other problems.
