### ISSUE TITLE
Xbuild report Run Script twice

### ISSUE THREAD

**Issue by regnerjr** [gfontenot/vim-xcodebuild#79]
When executing :Xbuild or :Xrun the output shows "Run Script" twice. 

```
Press ENTER or type command to continue
▸ Building WM To Go/WM To Go [Debug]
▸ Check Dependencies
▸ Running script 'Run Script'
▸ Running script 'Run Script'
▸ Build Succeeded
com.walmart.delivery: 9573

Press ENTER or type command to continue
```

Not sure why this is, but I wanted to report it and help debug if needed. 

Thanks.

**Comment by gfontenot** [comment]
At that point, it's out of our control. You should see the same thing if you run `xcodebuild` manually and pipe it over to `xcpretty`. Is it possible you actually do have a duplicate script phase in there?

**Comment by regnerjr** [comment]
Right. That is just the build output of xcpretty. Thanks again for your help.
I do indeed have 2 build phases both descriptively named "Run Script"

![screen shot 2016-08-25 at 4 52 11 pm](https://cloud.githubusercontent.com/assets/573579/17989762/95d64940-6ae4-11e6-85e0-a48295430dc4.png)

Thanks again for the help.
