### ISSUE TITLE
Using AsyncRun?

### ISSUE THREAD

**Issue by sgoodwin** [gfontenot/vim-xcodebuild#80]
I should be able to use AsyncRun as my runner right? (yay vim8.0!) I tried replacing the runner variable, but that made vim freeze up. Is there anything that would prevent this from happening you think?

**Comment by gfontenot** [comment]
Not that I know of? I'm not super familiar with how AsyncRun works. Is is just a normal command? As in can you do `:AsyncRun xcodebuild` manually and have it work?

**Comment by sgoodwin** [comment]
Right. That would start xcodebuild running in the background.

**Comment by gfontenot** [comment]
I'm not sure why that would cause any problems then. Mind posting your runner variable?

**Comment by sgoodwin** [comment]
`let g:xcode_runner_command = 'AsyncRun {cmd}'`
Where typing `:AsyncRun xcodebuild` runs xcodebuild in the background.

**Comment by gfontenot** [comment]
Yeah that should work fine. I'll look into this soon, unless you find a solution before me.

**Comment by sgoodwin** [comment]
I'm digging into vimscript/plugins stuff in general so I might. Will post if I do.

**Comment by gfontenot** [comment]
For reference, [this](https://github.com/gfontenot/vim-xcode/blob/master/plugin/xcode.vim#L132-L135) is the only place we're actually interacting with the runner template. And we're pulling from the user-defined config [here](https://github.com/gfontenot/vim-xcode/blob/master/plugin/xcode.vim#L304-L310)

**Comment by sgoodwin** [comment]
Turns out it was a difference in how things need to be escaped for AsyncRun compared to the runners you list in your docs. I'll have to work something else out, oh well!

**Comment by gfontenot** [comment]
Oh, I'd love to know more about this. Do you mind elaborating?

**Comment by sgoodwin** [comment]
So vim-xcode builds a string like this to execute:

`'AsyncRun! set -o pipefail; NSUnbufferedIO=YES xcrun xcodebuild build -project '\''./TheoryDrills.xcodeproj'\'' -scheme '\''TheoryDrills'\'' -destination "platform=iOS Simulator,name=iPhone SE" | xcpretty --color'`

The one that works with AsyncRun is like this:

`nnoremap <leader>b :AsyncRun xcodebuild -scheme TheoryDrils -destination name=iPhone\ SE,platform=iOS\ Simulator \| xcpretty<cr>`

the spaces in destination need to be escaped and basically nothing else. It splits the command on spaces for some reason before executing it, thus the need for escapes on the spaces in destination. Escapes anywhere else gives "command not found" errors because `"xcodebuild"` with quotes around it isn't a valid thing.
