### ISSUE TITLE
Option to prefer xcproject over xcworkspace (for schemes)

### ISSUE THREAD

**Issue by jandamm** [gfontenot/vim-xcodebuild#89]
When using Cocoapods you have a workspace where all the schemes of the pods and your own schemes exist.
Most of the time you don't want to run the pods schemes but only your own.

I would like to have an option to ignore the workspace for the list of your schemes.

If you don't like this option another way to fix this would be to look for Pods.xcodeproj and substract these schemes.

I'd try to implement this myself, if you'd be open to merge it 👍

**Comment by gfontenot** [comment]
Oh yeah this is a great idea! Maybe it makes the most sense to open up some kind of `g:xcode_scheme_source` option that users can set to override the default value (which would be the workspace/project as it works now)? That seems like the most flexible way to tackle it.

If you have the time and want to take this on, I'd love to see a PR and would be more than happy to review/merge it!

**Comment by jandamm** [comment]
I think this matches the current way of configuring the project well.
I'll add that.

I'd like to add g:xcode_ignore_pods where the workspace schemes subtracting Pods/Pods.xcodeproj schemes would be shown. What do you think of this option? I would suggest a default value of 0 to not change the current default behavior.

**Comment by gfontenot** [comment]
I think I'd like to avoid building in any CocoaPods specific knowledge here, honestly. Maybe a compromise would be like `g:xcode_scheme_source_ignore` which would let you specify projects/workspaces to ignore? Then in your vimrc you could do like:

```vimrc
let g:xcode_scheme_source_ignore = [
  \ "Pods/Pods.xcodeproj"
  \ ]
```

or whatever to filter out any cocoapods sources from any of your projects?

**Comment by mokagio** [comment]
Love the ignore idea.

**Comment by jandamm** [comment]
I've added the `xcode_scheme_source_ignore`. Unfortunately it is quite slow as it has to list schemes multiple times.

What do you think of `g:xcode_prefer_projects` which would result in ignoring any xcworkspace if there is a xcproject in the project root?
I think this would be the easiest solution (at least for me).

**Comment by jandamm** [comment]
I've written a [small plugin](https://github.com/jandamm/vim-projplugin) to source vim-files depending on the current project.
(Think of it as `ftplugin/*.vim` but using the cwd as project name)
Which fixes this issue for me.
